### ISSUE TITLE
Add CI to check that the .idl parses

### ISSUE THREAD

**Issue by bakkot** [shapesecurity/shift-spec#103]

**Comment by michaelficarra** [comment]
YES! We've made so many mistakes with missing semicolons and whatnot.

**Comment by michaelficarra** [comment]
I've enabled Travis for this repo, so we just need to make a `.travis.yml` file that calls a script that validates the IDL file.

**Comment by michaelficarra** [comment]
Also needs to check that `attribute-order.conf`is not missing any types/attributes and does not have any additional types/attributes.

**Comment by michaelficarra** [comment]
Fixed by #108.
