### ISSUE TITLE
ES2016: MemberBindings are allowed in places they ought not be

### ISSUE THREAD

**Issue by bakkot** [shapesecurity/shift-spec#104]
For example, a BindingWithDefault should not allow a MemberBinding. Nor should a Rest or a BindingPattern.

Potential fixes include having MemberBinding not implement Binding or having a new NonMemberBinding for variable declarations, catch parameters, parameters, rest elements, and BindingPatterns. I favor the former.

**Comment by michaelficarra** [comment]
These need to be allowed because `[a.b] = c` is a program, and we don't distinguish between binding targets and assignment targets in our AST. I'd rather not do that (it would introduce a large number of new nodes and create a decent amount of incompatibility), but it may be for the best.

**Comment by bakkot** [comment]
Wait, why is that a program? I see we accept it currently, but an [ArrayBindingPattern](https://tc39.github.io/ecma262/#prod-ArrayBindingPattern) is essentially a list of [BindingElement](https://tc39.github.io/ecma262/#prod-BindingElement)s, which are either patterns or BindingIdentifiers, possibly with defaults. I don't see how `[a.b] = c` is a program.

**Comment by michaelficarra** [comment]
It's not an ArrayBindingPattern, it's an [ArrayAssignmentPattern](https://tc39.github.io/ecma262/#prod-ArrayAssignmentPattern).

**Comment by bakkot** [comment]
Ah, ok. I'd prefer to distinguish between assignment targets and bindings, I guess, to avoid being able to represent `var [a.b]`. The introduction of MemberBinding is already going to introduce some amount of incompatibility, so this seems a good time for it.

**Comment by bakkot** [comment]
I believe this would only require the introduction of two new types, namely ArrayAssignmentTarget and ObjectAssignmentTarget (or similar less clunky names).

**Comment by michaelficarra** [comment]
Okay, that sounds reasonable. Please put together a PR.

**Comment by bakkot** [comment]
Fixed by #105 (cefb882).
