### ISSUE TITLE
UnknownDirective and UseStrictDirective overlap

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-spec#11]
An `UnknownDirective` with `value` "use strict" would re-parse as a UseStrictDirective. I think it was a bad idea splitting these things out. For the next version, I think we should have a single Directive node.

**Comment by ikarienator** [comment]
Not exactly... correct me if I'm wrong: the value is the unescaped value of the string literal. We might need to rename `value` to `raw` or have a boolean `raw` flag on it.

**Comment by michaelficarra** [comment]
The value is the raw representation of the directive.

**Comment by michaelficarra** [comment]
Fixed on `es6` branch.
