### ISSUE TITLE
PropertyName kind can conflict with value

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-spec#12]
For instance, a PropertyName with `kind` of "number" can have a non-numeric `value`, and a PropertyName with a `kind` of "identifier" can have a non-IdentifierName `value`. Is there a better way we can represent this?

**Comment by ikarienator** [comment]
In the java version, we used constructor overloading to restrict these problems.

**Comment by michaelficarra** [comment]
I believe we should just remove `kind` altogether. It was only there as a holdover from SpiderMonkey that preserved concrete syntax info.

**Comment by ikarienator** [comment]
I agree. But a drawback of that will be when we codegen a certain `PropertyName`, we always have to test which kind of it we want to generate.

**Comment by michaelficarra** [comment]
You can always safely quote it if you want. No test needed.

**Comment by ikarienator** [comment]
That'll end up to be a slightly longer code.

**Comment by michaelficarra** [comment]
I didn't say you *had* to do it, just that you *could* do it without testing for IdentifierName/numeric value by always quoting it.

**Comment by michaelficarra** [comment]
Fixes on `es6` branch by removing `StaticPropertyName::kind`.
