### ISSUE TITLE
FunctionExpression should be a LiteralExpression

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-spec#16]
Currently, it's a `PrimaryExpression`. Rename it to `LiteralFunctionExpression`?

**Comment by ikarienator** [comment]
Our definition of Literals are single-tokened source code elements whose value is fixed. They are strictly referential transparent and any literal should equal to another literal if their source code are the same. 

Same for array expression, object expression and template string expressions.

Besides: http://es5.github.io/#x7.8

**Comment by michaelficarra** [comment]
Works for me.
