### ISSUE TITLE
support destructuring in ES6 branch

### ISSUE THREAD

**Issue by kevinb7** [shapesecurity/shift-spec#18]
ES6 allows function declarations such as ```function foo(x, y, { a, b, c = "true" }) { ... }```.  Looking at the current interface I don't see how round tripping code -> AST -> code could maintain this example.

> interface Function {
>     attribute BindingWithDefault[] parameters;
>     attribute BindingIdentifier? restParameter;
> };

**Comment by kevinb7** [comment]
I had a quick look at ```VariableDeclarator``` and it doesn't seem like it'd be able to handle round tripping stuff like:
```
var [x,y,z] = [1,2,3];
var { width:w, height:h } = { width: 320, height: 200 }
```

**Comment by michaelficarra** [comment]
I believe we're properly handling function parameters after a review of `BindingWithDefault`. But you're right, I've missed `VariableDeclarator`'s `binding`. I'll fix that right now.

**Comment by kevinb7** [comment]
In the function declaration example I gave, what would { a, b, c = "true" } be represented by in the AST?  It's a single anonymous parameter with some of it's properties being extracted.  I don't see how 
```
interface BindingWithDefault : Node {
  attribute Binding binding;
  attribute Expression initializer;
};
```
can model this scenario?  I was going to boot up the new parser you guys are working but it appears that it doesn't support destructuring yet: https://github.com/shapesecurity/shift-parser-js/issues/8.

How can I best help get more of those checkboxes checked?

**Comment by michaelficarra** [comment]
You are totally right. I was assuming there was a fall-through from `BindingWithDefault` to `Binding`, but `initializer` is not optional. I've added an `or Binding` to each use of `BindingWithDefault`. Check out #19 and let me know if it looks good to you.

On contributing to the parser, we would love help with that. Just add a note saying you're working on any issue that hasn't yet been started by someone else, or create a new issue for any feature that doesn't yet have one.

**Comment by kevinb7** [comment]
Another thing to be aware of that I didn't mention in my initial examples was that the destructuring can be nested, e.g. ```var [ first, { x: secondX } ] = arrayOfPoints``` is totally valid.  I had a quick look at the spec and they provide a grammar for these structures: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-binding-patterns.  It might be good to use this as a template for the binding part of the idl.

**Comment by michaelficarra** [comment]
In what way is it still insufficient after the above PR? Your example would be

```js
{ type: 'VariableDeclaration',
  kind: 'var',
  declarators:
   [ { type: 'VariableDeclarator',
       binding:
        { type: 'ArrayBinding',
          elements:
           [ { type: 'BindingIdentifier',
               identifier: { type: 'Identifier', name: 'first' } },
             { type: 'ObjectBinding',
               properties:
                [ { type: 'BindingPropertyProperty',
                    propertyName: { type: 'StaticPropertyName', value: 'x' },
                    binding:
                     { type: 'BindingIdentifier',
                       identifier: { type: 'Identifier', name: 'secondX' } } } ] } ],
          restElement: null },
       init:
        { type: 'IdentifierExpression',
          identifier:
           { type: 'Identifier',
             name: 'arrayOfPoints' } } } ] }
```

**Comment by kevinb7** [comment]
I missed the fact that BindingWithDefault contains a ```binding``` reference.  I take back my earlier comment about using the spec's grammar as a template.  It's quite verbose.  The IDL collapses quite a few of the rules from the spec.  The ```initializer``` expression on ```BindingWithDefault``` should be optional.

The AST makes sense but it doesn't seem to match the IDL.  In the IDL, ArrayBinding's "elements" property is of type ```BindingWithDefault?[]``` , but in AST above the elements array contains a BindingIdentifier and ```ObjectBinding``` which inherit from ```Binding``` not ```BindingWithDefault```.  I'm probably missing something.

The spec also has allows for skipping elements in an _ArrayBindingPattern_, e.g. ```let [x, ,y] = [1,2,3]```.  This is represented by the _BindingElementList_ in the spec.  Can this be achieved by allowing ```ArrayBinding```'s ```elements``` property to be a sparse array with elements that are undefined representing the _Elision_ tokens from the spec?

**Comment by michaelficarra** [comment]
@kevinb7: Check out #19. The example above (where I was careful to state "after the above PR") was assuming #19 has been merged, which is why `ArrayBinding` allows both `BindingWithDefault` and `Binding`. Making `BindingWithDefault`'s `initializer` optional would have been another way to solve it, but would have also made ASTs unnecessarily deep and less conducive to transformation.

**Comment by kevinb7** [comment]
@michaelficarra That makes sense; keeping AST depth in check is good rationale.  As for allowing gaps in the ```elements```, is that why ```attribute BindingWithDefault?[] elements;``` has a "?"?  Does ```BindingWithDefault?``` == ```(BindingWithDefault or null)```?

**Comment by michaelficarra** [comment]
Yep. For questions like that, see [the Web IDL specification](http://www.w3.org/TR/WebIDL/) (in particular [3.10.21](http://www.w3.org/TR/WebIDL/#idl-nullable-type)).

**Comment by kevinb7** [comment]
Searched for "IDL"... should've searched for "Web IDL".  Thanks for the link.
