### ISSUE TITLE
ES6: remove unnecessary BindingIdentifier wrapper when possible?

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-spec#21]
It appears that `BindingPropertyIdentifier` and `ArrayBinding` can just have an `Identifier` child instead of a `BindingIdentifier`. This is good in that it leads to shallower trees, but bad in that it may make searching for `Identifier` nodes in binding position more difficult.

**Comment by ikarienator** [comment]
Shall we close this?
