### ISSUE TITLE
LabeledStatement -> LabelledStatement?

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-spec#49]
We have a `LabeledStatement` node, but the spec term is `LabelledStatement`. Should we align with it?

**Comment by jsoverson** [comment]
For reference : https://books.google.com/ngrams/graph?content=labeled%2Clabelled&year_start=1950&year_end=2008&corpus=0&smoothing=3&share=&direct_url=t1%3B%2Clabeled%3B%2Cc0%3B.t1%3B%2Clabelled%3B%2Cc0

Adherence to the spec is nice but this would be better to align on common usage in actual code to avoid having people write statements like `var labeledStatement = new LabelledStatement()`

Github's search is fuzzy only so matches both, but I can scrape the search results to find the common usage across developers.

**Comment by jsoverson** [comment]
```
171 total results in first 1000 returned by github
145 for labeled/labeler/labeling
27 for labelled/labeller/labelling
```

**Comment by michaelficarra** [comment]
Those results are going to be skewed due to SpiderMonkey AST using `LabeledStatement`, and should not affect our decision.

**Comment by jsoverson** [comment]
None of those results parsed included 'labeledstatement'

**Comment by ikarienator** [comment]
I've absolutely no incentive to bump major version on every single tool we have so we can spell like a Brit.

**Comment by michaelficarra** [comment]
This is the ES6 milestone, so there will be a major version bump anyway. And it's not because it's British (aka English), it's because of how it's spelled in the spec.

**Comment by ikarienator** [comment]
So you want to drop the backward compatibility completely? I don't know if backward compatibility is completely useless.

**Comment by michaelficarra** [comment]
I was just putting it out there. Closing.
