### ISSUE TITLE
add prose sections describing what each attribute represents

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-spec#69]
Currently, when readers see

``` idl
interface BinaryExpression : Expression {
  attribute BinaryOperator operator;
  attribute Expression left;
  attribute Expression right;
};
```

they must assume that `left` is the representation of the left operand and `right` is the representation of the right operand. We should make this clear with prose in comments.

**Comment by ikarienator** [comment]
This seems like a bug to me. We shall move `operator` in between.

Besides, it will be awesome if we can actually have comments on all the nodes to link to the corresponding part of the ES6 spec.
