### ISSUE TITLE
Separate index.js from idl spec?

### ISSUE THREAD

**Issue by jsoverson** [shapesecurity/shift-spec#72]
That way breaking changes to the generated files (like between 2.0.x and 2.1.x) don't force a major semver update to the spec itself.

**Comment by michaelficarra** [comment]
:+1:

**Comment by ikarienator** [comment]
I agree. But I thought the change was an additive change? no?

**Comment by jsoverson** [comment]
type changed to typeName and other properties were moved to a fields array
between 2.0.x and 2.1.x

**Comment by ikarienator** [comment]
Ah, that was right... It shouldn't happen...

**Comment by michaelficarra** [comment]
https://github.com/shapesecurity/shift-spec-js
