### ISSUE TITLE
consider splitting ForInStatement with binding and ForInStatement with VariableDeclaration

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-spec#8]
The reasoning behind this is that a ForInStatement with a VariableDeclaration `left` may only have a single declarator. This must be [validated with our validator](https://github.com/shapesecurity/shift-validator-js/blob/51bc6c30d3f673e60e70642d31005ba04bc81e9e/src/index.js#L84-L86). Instead, we should just represent it as a VariableDeclarationKind and a VariableDeclarator. The downside to this would be that uniform VariableDeclaration handling would not apply in this case. I'm not sure which is better.

**Comment by ikarienator** [comment]
I will go a step further to separate all four for statements and remove the `Either` kind.

**Comment by michaelficarra** [comment]
@ikarienator Thoughts on this? I am neutral on it, and trying to avoid extra work before publishing the ES6 standard. Close?
