### ISSUE TITLE
restrict catch parameter to disallow member expressions

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-spec#81]
Currently, catch parameters are Binding nodes, but they can be a union of ObjectBinding, ArrayBinding, and BindingIdentifier instead. This should be included in the ES7 branch, as there's no reason to make a breaking change for this enhancement.

**Comment by michaelficarra** [comment]
Same problem and fix applies to VariableDeclarator.

**Comment by yaylinda** [comment]
fixed by #83.
